on: 
  push:
    paths:
        - '**/*.md'

jobs:
  verify-syntax:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: proselint ./**/*.md
